apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::123945545943:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-N9MARDPU9K9Z
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::123945545943:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T19:23:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1928"
  uid: 03f4ff77-d83e-4d89-9f34-feaa09e7c68e
