apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::123945545943:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EPEUL2SC6YSI\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolelearn: arn:aws:iam::123945545943:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build      \n  \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T23:33:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "359231"
  uid: 38ad4cc2-8f38-41e5-ad42-f6b7a82ee7bb
